# See https://docs.github.com/en/actions/guides/building-and-testing-python
name: CI (pip)

on:
  push:
    branches:
      - '**' # This will trigger the action for all branches
  pull_request:
    branches:
      - main # Specify the branches for which pull_request events should trigger the action

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest', 'windows-latest']   # with MySQL service, we now only run on ubuntu
        python-version: [3.12]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Initial checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Conditional step for push events
      - name: Run on push
        if: github.event_name == 'push'
        run: echo "This runs on a push to any branch"

      # Conditional step for pull_request events
      - name: Run on pull request
        if: github.event_name == 'pull_request'
        run: echo "This runs on a pull request to the main branch"


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: install Ubuntu-specific stuff
        if: startsWith(matrix.os, 'ubuntu')
        run: make install-ubuntu

      - name: install Mac-specific stuff
        if: startsWith(matrix.os, 'macos')
        run: make install-macos

      - name: install Windows-specific stuff
        if: startsWith(matrix.os, 'windows')
        run: make install-windows

      - name: Lint with pylint
        run: make pylint

      - name: Run coverage test (only on ubuntu)
        if: startsWith(matrix.os, 'ubuntu')
        run: make coverage

      - name: Upload to codecov.io
        if: startsWith(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        with:
          verbose: true


      - name: List all files at end
        if: startsWith(matrix.os, 'ubuntu') or startsWith(matrix.os, 'macos')
        run: find . -ls
