# See https://docs.github.com/en/actions/guides/building-and-testing-python
# 2020-02-20 slg - For Dreamhost, we are now using Python 3.9 and Ubuntu-18.04
# There is no way to generate a random password that can be used in the services section, so that will need to be moved to a repository secret of RANDOM_PASSWORD
name: CI (pip)
on: [push, pull_request]

jobs:
  build:
    strategy:
      matrix:
        os: ['ubuntu-latest', 'macos-latest']   # with MySQL service, we now only run on ubuntu
        python-version: [3.11]   # installed version on Dreamhost
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint with pylint
        run: |
          make pylint

      - name: Validate database access
        run: |
          python3 -m pytest -x --log-cli-level=DEBUG tests/dbreader_test.py

      - name: Validate app framework
        run: |
          python3 -m pytest -x --log-cli-level=DEBUG tests/app_test.py -k test_templates

      - name: Run coverage test
        if: startsWith(matrix.os, 'ubuntu')
        env:
          SKIP_ENDPOINT_TEST:   ${{ vars.SKIP_ENDPOINT_TEST }}
        run: |
          CHROME_PATH=${{ steps.setup-chrome.outputs.chrome-path }} make coverage

      - name: Upload to codecov.io
        if: startsWith(matrix.os, 'ubuntu')
        uses: codecov/codecov-action@v3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          verbose: true
          files: ./coverage.xml

      - name: Show files in directory
        run: |
          make coverage
          ls -l
